# Generated by Django 5.2 on 2025-05-10 09:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 10, 15, 28, 7, 312990)),
        ),
    ]
