# Generated by Django 5.2.1 on 2025-05-13 22:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_followerscount_likepost_alter_post_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tx_hash',
            field=models.CharField(blank=True, max_length=66, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 14, 3, 4, 22, 498351)),
        ),
    ]
