# Generated by Django 5.2.1 on 2025-05-13 22:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_post_tx_hash_alter_post_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='blockchain_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 14, 3, 49, 31, 129354)),
        ),
    ]
